/* Drop Tables */
DROP TABLE AUTHORITY CASCADE CONSTRAINTS;
DROP TABLE BCNO CASCADE CONSTRAINTS;
DROP TABLE BOARD_COMMNET_REPORTS CASCADE CONSTRAINTS;
DROP TABLE BOARD_COMMENT CASCADE CONSTRAINTS;
DROP TABLE BOARD_IMAGE CASCADE CONSTRAINTS;
DROP TABLE BOARD_LIKES CASCADE CONSTRAINTS;
DROP TABLE BOARD_REPORTS CASCADE CONSTRAINTS;
DROP TABLE BOARD_SCRAPS CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE CALENDAR_LIKES CASCADE CONSTRAINTS;
DROP TABLE DIET CASCADE CONSTRAINTS;
DROP TABLE EXERCISE CASCADE CONSTRAINTS;
DROP TABLE CALENDAR CASCADE CONSTRAINTS;
DROP TABLE CHATTING_CHATROOM CASCADE CONSTRAINTS;
DROP TABLE CHATTING_LIST CASCADE CONSTRAINTS;
DROP TABLE UNFREEZE CASCADE CONSTRAINTS;
DROP TABLE BLACK_LIST CASCADE CONSTRAINTS;
DROP TABLE DECLARATION CASCADE CONSTRAINTS;
DROP TABLE FRIENDSHIP CASCADE CONSTRAINTS;
DROP TABLE GAMEROOM_RANKING CASCADE CONSTRAINTS;
DROP TABLE INBODY CASCADE CONSTRAINTS;
DROP TABLE NOTIFICATION CASCADE CONSTRAINTS;
DROP TABLE PAY CASCADE CONSTRAINTS;
DROP TABLE SOCIAL CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE CHATTING CASCADE CONSTRAINTS;
DROP TABLE GAMEROOM CASCADE CONSTRAINTS;

/* Drop Sequences */

DROP SEQUENCE SEQ_ACCOUNT_ACCOUNT_NO;
DROP SEQUENCE SEQ_BLACK_LIST_BLACK_NO;
DROP SEQUENCE SEQ_BOARD_BNO;
DROP SEQUENCE SEQ_BOARD_COMMENT_BCNO;
DROP SEQUENCE SEQ_CALENDAR_CALENDAR_NO;
DROP SEQUENCE SEQ_CHATTING_CHATTING_NO;
DROP SEQUENCE SEQ_DECLARATION_DECLARATION_NO;
DROP SEQUENCE SEQ_GAMEROOM_GAMEROOM_NO;

/* Create Sequences */
CREATE SEQUENCE SEQ_ACCOUNT_ACCOUNT_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_BLACK_LIST_BLACK_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_BOARD_BNO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_BOARD_COMMENT_BCNO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_CALENDAR_CALENDAR_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_CHATTING_CHATTING_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_DECLARATION_DECLARATION_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_GAMEROOM_GAMEROOM_NO INCREMENT BY 1 START WITH 1;

/* Create Tables */
-- 회원 정보
CREATE TABLE ACCOUNT
(
	-- 회원 일렬번호
	ACCOUNT_NO number NOT NULL,
	-- 이메일
	EMAIL nvarchar2(100) NOT NULL UNIQUE,
	-- 비밀번호
	PASSWORD nvarchar2(50) NOT NULL,
	-- 회원 이름
	NAME nvarchar2(20) NOT NULL,
	-- 성별
	GENDER char(1) NOT NULL,
	-- 나이
	AGE number(3,0) NOT NULL,
	-- 주소
	ADDRESS nvarchar2(100) NOT NULL,
	-- 관심분야
	hobby char(1) NOT NULL,
	-- 가입일
	ENROLL_DATE date DEFAULT SYSDATE NOT NULL,
	-- 프로필 이미지
	IMAGE nvarchar2(100),
	PRIMARY KEY (ACCOUNT_NO)
);

-- 회원 권한
CREATE TABLE AUTHORITY
(
	-- 회원 일렬번호
	ACCOUNT_NO number NOT NULL,
	-- AUTHORITY
	AUTHORITY nvarchar2(20) DEFAULT 'ROLE_USER' NOT NULL
);

-- 댓글 좋아요
CREATE TABLE BCNO
(
	-- 게시글 댓글 일렬번호
	BCNO number NOT NULL,
	-- 회원 일렬번호
	ACCOUNT_NO number NOT NULL,
	-- 좋아요 누른 날짜
	LIKE_DATE date DEFAULT SYSDATE NOT NULL
);

-- 회원 정지 테이블
CREATE TABLE BLACK_LIST
(
	-- 정지 일렬번호
	BLACK_NO number NOT NULL,
	-- 신고 알렬번호
	DECLARATION_NO number NOT NULL,
	-- 정지일
	BLACK_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (BLACK_NO)
);

-- 게시글 목록
CREATE TABLE BOARD
(
	-- 게시글 일렬번호
	BNO number NOT NULL,
	-- 회원 일렬번호
	ACCOUNT_NO number NOT NULL,
	-- 게시일
	POSTDATE date DEFAULT SYSDATE NOT NULL,
	-- 제목
	TITLE nvarchar2(100) NOT NULL,
	-- HIT_COUNT
	HIT_COUNT number DEFAULT 0,
	-- 게시글 종류
	BOARD_CATEGORY number NOT NULL,
	-- 첨부 이미지들
	BOARD_IMAGES nvarchar2(100),
	-- 내용
	BOARD_COMMENT nvarchar2(2000) NOT NULL,
	-- 게시글에 첨부된 주소
	ADDRESS nvarchar2(100),
	-- 수정일
	EDIT_DATE date,
	PRIMARY KEY (BNO)
);

-- 게시글 댓글 목록
CREATE TABLE BOARD_COMMENT
(
	-- 게시글 댓글 일렬번호
	BCNO number NOT NULL,
	-- 게시글 일렬번호
	BNO number NOT NULL,
	-- 회원 일렬번호
	ACCOUNT_NO number NOT NULL,
	-- 댓글 작성일
	POST_DATE date DEFAULT SYSDATE NOT NULL,
	-- 댓글 내용
	BC_COMMENT nvarchar2(200) NOT NULL,
	-- 답글 일련번호
	REPLY_NO number,
	-- 댓글 수정일
	EDIT_DATE date,
	PRIMARY KEY (BCNO)
);


-- 신고된 댓글 목록
CREATE TABLE BOARD_COMMNET_REPORTS
(
	-- 게시글 댓글 일렬번호
	BCNO number NOT NULL,
	-- 회원 일렬번호
	ACCOUNT_NO number NOT NULL,
	-- 댓글 신고한 이유
	REPORT_REASON nvarchar2(200),
	-- REPORT_DATE
	REPORT_DATE date DEFAULT SYSDATE NOT NULL
);


-- 게시글 이미지
CREATE TABLE BOARD_IMAGE
(
	-- 게시글 일렬번호
	BNO number NOT NULL,
	-- 이미지
	IMAGE nvarchar2(100) NOT NULL,
	-- 이미지 라인 위치
	LINE_LOC number NOT NULL
);


-- 게시글 좋아요 수
CREATE TABLE BOARD_LIKES
(
	-- 게시글 일렬번호
	BNO number NOT NULL,
	-- 회원 일렬번호
	ACCOUNT_NO number NOT NULL,
	-- 좋아요 누른 날짜
	LIKE_DATE date DEFAULT SYSDATE NOT NULL
);


-- 게시글 신고 테이블
CREATE TABLE BOARD_REPORTS
(
	-- 신고된 게시글 일렬번호
	BNO number NOT NULL,
	-- 신고한 회원 일렬번호
	ACCOUNT_NO number NOT NULL,
	-- 게시글 신고 사유
	REPORT_COMMENT nvarchar2(100) NOT NULL,
	-- REPORT_DATE
	REPORT_DATE date DEFAULT SYSDATE NOT NULL
);


-- 게시글 스크랩 목록
CREATE TABLE BOARD_SCRAPS
(
	-- 회원 일렬번호
	ACCOUNT_NO number NOT NULL,
	-- 게시글 일렬번호
	BNO number NOT NULL
);


-- 캘린더
CREATE TABLE CALENDAR
(
	-- 캘린더 일련번호
	CALENDAR_NO number NOT NULL,
	-- 회원 일렬번호
	ACCOUNT_NO number NOT NULL,
	-- 제목
	DESCRIPTION nvarchar2(100) NOT NULL,
	-- 메모
	MEMO nvarchar2(100) NOT NULL,
	-- 시작 날짜
	START_POSTDATE date DEFAULT SYSDATE,
	-- 끝 날짜
	END_POSTDATE date DEFAULT SYSDATE,
	PRIMARY KEY (CALENDAR_NO)
);


-- 캘린더 좋아요 수
CREATE TABLE CALENDAR_LIKES
(
	-- 캘린더 일련번호
	CALENDAR_NO number NOT NULL,
	-- 좋아요 누른 날짜
	LIKE_DATE date DEFAULT SYSDATE
);


-- 채팅방
CREATE TABLE CHATTING
(
	-- 채팅방 일렬번호
	CHATTING_NO number NOT NULL,
	-- OPENING_DATE
	OPENING_DATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (CHATTING_NO)
);


-- 채팅 대화방
CREATE TABLE CHATTING_CHATROOM
(
	-- 채팅방 일렬번호
	CHATTING_NO number NOT NULL,
	-- 회원 일렬번호
	ACCOUNT_NO number NOT NULL,
	-- POST_DATE
	POST_DATE date DEFAULT SYSDATE NOT NULL,
	-- 채팅 내용
	CHAT_COMMENT nvarchar2(200) NOT NULL,
	-- 첨부한 파일
	ATTACH_FILE nvarchar2(200),
	-- 공지 내용
	NOTICE_COMMENT nvarchar2(100)
);


-- 채팅방 목록
CREATE TABLE CHATTING_LIST
(
	-- 채팅방 일렬번호
	CHATTING_NO number NOT NULL,
	-- 회원 일렬번호
	ACCOUNT_NO number NOT NULL,
	-- 채팅방 이름 별칭
	CHATTING_NICK nvarchar2(20)
);


-- 사용자 신고 테이블
CREATE TABLE DECLARATION
(
	-- 신고 알렬번호
	DECLARATION_NO number NOT NULL,
	-- 회원 일렬번호
	ACCOUNT_NO number NOT NULL,
	-- 신고받은 사유
	DECLARATION_REASON nvarchar2(500),
	PRIMARY KEY (DECLARATION_NO)
);


-- 식단
CREATE TABLE DIET
(
	-- 캘린더 일련번호
	CALENDAR_NO number NOT NULL,
	-- 음식 사진
	DIET_IMAGE nvarchar2(50),
	-- 음식 종류
	FOOD nvarchar2(100) NOT NULL,
	-- 소비 칼로리
	FOOD_WEIGHT number NOT NULL
);


-- 운동 기록
CREATE TABLE EXERCISE
(
	-- 캘린더 일련번호
	CALENDAR_NO number NOT NULL,
	-- 운동 종류
	CATEGORY nvarchar2(50) NOT NULL,
	-- 평균 정확도
	ACCURACY number NOT NULL,
	-- 총 운동 횟수
	COUNTS number NOT NULL,
	-- 무게
	WEIGHT number
);


-- 친구 정보
CREATE TABLE FRIENDSHIP
(
	-- 회원 일렬번호
	ACCOUNT_NO number NOT NULL,
	-- 친구 아이디
	OPPONENT_NO number NOT NULL,
	-- NICKNAME
	NICKNAME nvarchar2(20) UNIQUE,
	-- 친구 상태
	REALATION char(1) DEFAULT 'S' NOT NULL
);


-- 게임방
CREATE TABLE GAMEROOM
(
	-- 게임방 일렬번호
	GAMEROOM_NO number NOT NULL,
	-- 게임방 모드
	GAME_MODE char(1) NOT NULL,
	PRIMARY KEY (GAMEROOM_NO)
);


-- 인게임 랭킹
CREATE TABLE GAMEROOM_RANKING
(
	-- 게임방 일렬번호
	GAMEROOM_NO number NOT NULL,
	-- 회원 일렬번호
	ACCOUNT_NO number NOT NULL,
	-- 게임날짜
	GAME_DATE date DEFAULT SYSDATE NOT NULL,
	-- 인게임 순위
	GAMEROOM_RANK number NOT NULL,
	-- 점수
	GAMEROOM_POINT number NOT NULL
);


-- 인바디 정보
CREATE TABLE INBODY
(
	-- 회원 일렬번호
	ACCOUNT_NO number NOT NULL,
	-- 인바디 저장 날짜
	POST_DATE date DEFAULT SYSDATE NOT NULL,
	-- 키
	HEIGHT number NOT NULL,
	-- 체중
	WEIGHT number NOT NULL,
	-- 골격근량
	SKELETAL_MUSCLE number(6,2),
	-- 체지방률
	BODY_FAT_MASS number(6,2),
	-- 체지방률
	BODY_FAT_PERCENTAGE number(6,2),
	-- 복부지방률
	ABDOMINAL_FAT_RATE number(6,2),
	-- 기초대사량
	BASAL_METABOLIC_RATE number(6,2)
);


-- 알림
CREATE TABLE NOTIFICATION
(
	-- 회원 일렬번호
	ACCOUNT_NO number NOT NULL,
	-- 알림종류
	NOTIFICATION_CATEGORY char(1) NOT NULL,
	-- 알림 온 게시글번호
	NOTIFICATION_NUMBERING number NOT NULL,
	-- 알림을 준 상대방 번호
	OPPONENT_NO number NOT NULL,
	-- NOTICE_DATE
	NOTICE_DATE date DEFAULT SYSDATE NOT NULL
);


-- 결제 테이블
CREATE TABLE PAY
(
	-- 회원 일렬번호
	ACCOUNT_NO number NOT NULL,
	-- 결제 날짜
	PAY_DATE date DEFAULT SYSDATE NOT NULL,
	-- 결재 종류
	PAY_TYPE char(1) NOT NULL,
	-- 현재 소유 금액
	NOW_POINT number NOT NULL
);


-- 소셜
CREATE TABLE SOCIAL
(
	-- 회원 일렬번호
	ACCOUNT_NO number NOT NULL,
	-- 소셜 도메인
	SOCIAL_CATEGORY nvarchar2(50) NOT NULL
);


-- 회원 정지 해제 테이블
CREATE TABLE UNFREEZE
(
	-- 정지 일렬번호
	BLACK_NO number NOT NULL,
	-- 정지 해제일
	UNFREEZE_DATE date DEFAULT SYSDATE,
	-- 해제 이유
	UNFREEZE_RESON nvarchar2(500)
);



/* Create Foreign Keys */

ALTER TABLE AUTHORITY
	ADD FOREIGN KEY (ACCOUNT_NO)
	REFERENCES ACCOUNT (ACCOUNT_NO)
;


ALTER TABLE BCNO
	ADD FOREIGN KEY (ACCOUNT_NO)
	REFERENCES ACCOUNT (ACCOUNT_NO)
;


ALTER TABLE BOARD
	ADD FOREIGN KEY (ACCOUNT_NO)
	REFERENCES ACCOUNT (ACCOUNT_NO)
;


ALTER TABLE BOARD_COMMENT
	ADD FOREIGN KEY (ACCOUNT_NO)
	REFERENCES ACCOUNT (ACCOUNT_NO)
;


ALTER TABLE BOARD_COMMNET_REPORTS
	ADD FOREIGN KEY (ACCOUNT_NO)
	REFERENCES ACCOUNT (ACCOUNT_NO)
;


ALTER TABLE BOARD_LIKES
	ADD FOREIGN KEY (ACCOUNT_NO)
	REFERENCES ACCOUNT (ACCOUNT_NO)
;


ALTER TABLE BOARD_REPORTS
	ADD FOREIGN KEY (ACCOUNT_NO)
	REFERENCES ACCOUNT (ACCOUNT_NO)
;


ALTER TABLE BOARD_SCRAPS
	ADD FOREIGN KEY (ACCOUNT_NO)
	REFERENCES ACCOUNT (ACCOUNT_NO)
;


ALTER TABLE CALENDAR
	ADD FOREIGN KEY (ACCOUNT_NO)
	REFERENCES ACCOUNT (ACCOUNT_NO)
;


ALTER TABLE CHATTING_CHATROOM
	ADD FOREIGN KEY (ACCOUNT_NO)
	REFERENCES ACCOUNT (ACCOUNT_NO)
;


ALTER TABLE CHATTING_LIST
	ADD FOREIGN KEY (ACCOUNT_NO)
	REFERENCES ACCOUNT (ACCOUNT_NO)
;


ALTER TABLE DECLARATION
	ADD FOREIGN KEY (ACCOUNT_NO)
	REFERENCES ACCOUNT (ACCOUNT_NO)
;


ALTER TABLE FRIENDSHIP
	ADD FOREIGN KEY (ACCOUNT_NO)
	REFERENCES ACCOUNT (ACCOUNT_NO)
;


ALTER TABLE GAMEROOM_RANKING
	ADD FOREIGN KEY (ACCOUNT_NO)
	REFERENCES ACCOUNT (ACCOUNT_NO)
;


ALTER TABLE INBODY
	ADD FOREIGN KEY (ACCOUNT_NO)
	REFERENCES ACCOUNT (ACCOUNT_NO)
;


ALTER TABLE NOTIFICATION
	ADD FOREIGN KEY (ACCOUNT_NO)
	REFERENCES ACCOUNT (ACCOUNT_NO)
;


ALTER TABLE PAY
	ADD FOREIGN KEY (ACCOUNT_NO)
	REFERENCES ACCOUNT (ACCOUNT_NO)
;


ALTER TABLE SOCIAL
	ADD FOREIGN KEY (ACCOUNT_NO)
	REFERENCES ACCOUNT (ACCOUNT_NO)
;


ALTER TABLE UNFREEZE
	ADD FOREIGN KEY (BLACK_NO)
	REFERENCES BLACK_LIST (BLACK_NO)
;


ALTER TABLE BOARD_COMMENT
	ADD FOREIGN KEY (BNO)
	REFERENCES BOARD (BNO)
;


ALTER TABLE BOARD_IMAGE
	ADD FOREIGN KEY (BNO)
	REFERENCES BOARD (BNO)
;


ALTER TABLE BOARD_LIKES
	ADD FOREIGN KEY (BNO)
	REFERENCES BOARD (BNO)
;


ALTER TABLE BOARD_REPORTS
	ADD FOREIGN KEY (BNO)
	REFERENCES BOARD (BNO)
;


ALTER TABLE BOARD_SCRAPS
	ADD FOREIGN KEY (BNO)
	REFERENCES BOARD (BNO)
;


ALTER TABLE BCNO
	ADD FOREIGN KEY (BCNO)
	REFERENCES BOARD_COMMENT (BCNO)
;


ALTER TABLE BOARD_COMMNET_REPORTS
	ADD FOREIGN KEY (BCNO)
	REFERENCES BOARD_COMMENT (BCNO)
;


ALTER TABLE CALENDAR_LIKES
	ADD FOREIGN KEY (CALENDAR_NO)
	REFERENCES CALENDAR (CALENDAR_NO)
;


ALTER TABLE DIET
	ADD FOREIGN KEY (CALENDAR_NO)
	REFERENCES CALENDAR (CALENDAR_NO)
;


ALTER TABLE EXERCISE
	ADD FOREIGN KEY (CALENDAR_NO)
	REFERENCES CALENDAR (CALENDAR_NO)
;


ALTER TABLE CHATTING_CHATROOM
	ADD FOREIGN KEY (CHATTING_NO)
	REFERENCES CHATTING (CHATTING_NO)
;


ALTER TABLE CHATTING_LIST
	ADD FOREIGN KEY (CHATTING_NO)
	REFERENCES CHATTING (CHATTING_NO)
;


ALTER TABLE BLACK_LIST
	ADD FOREIGN KEY (DECLARATION_NO)
	REFERENCES DECLARATION (DECLARATION_NO)
;


ALTER TABLE GAMEROOM_RANKING
	ADD FOREIGN KEY (GAMEROOM_NO)
	REFERENCES GAMEROOM (GAMEROOM_NO)
;




